project:
  type: website
  resources: 
    - "documents/"
    - "images/"

website:
  title: "Tyler Pace"
  navbar:
    title: "<span title='Home'>Tyler Pace</span>"
    background: primary
    search: true
    left:
      - href: pages/about.qmd
        text: About
      - href: pages/projects.qmd
        text: Projects
      - href: pages/contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/tpace31
        aria-label: GitHub
      - icon: linkedin
        href: http://www.linkedin.com/in/pace-tyler
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:tylerjpace1@gmail.com
        aria-label: Email

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false